amp: false
aspect_ratio: fit
batch_size: 32
check_image_files: false
class_names:
- none
- normal
- s0
- s0_s1
- s0_s1_s2
- s0_s1_s2_s3
- s0_s1_s2_s3_s4
- s0_s1_s2_s3_s4_s5
- s0_s1_s2_s3_s4_s5_s6
- s0_s1_s2_s3_s4_s6
- s0_s1_s2_s3_s5
- s0_s1_s2_s3_s5_s6
- s0_s1_s2_s3_s6
- s0_s1_s2_s4
- s0_s1_s2_s4_s5
- s0_s1_s2_s4_s5_s6
- s0_s1_s2_s4_s6
- s0_s1_s2_s5
- s0_s1_s2_s5_s6
- s0_s1_s2_s6
- s0_s1_s3
- s0_s1_s3_s4
- s0_s1_s3_s4_s5
- s0_s1_s3_s4_s5_s6
- s0_s1_s3_s4_s6
- s0_s1_s3_s5
- s0_s1_s3_s5_s6
- s0_s1_s3_s6
- s0_s1_s4
- s0_s1_s4_s5
- s0_s1_s4_s5_s6
- s0_s1_s4_s6
- s0_s1_s5
- s0_s1_s5_s6
- s0_s1_s6
- s0_s2
- s0_s2_s3
- s0_s2_s3_s4
- s0_s2_s3_s4_s5
- s0_s2_s3_s4_s5_s6
- s0_s2_s3_s4_s6
- s0_s2_s3_s5
- s0_s2_s3_s5_s6
- s0_s2_s3_s6
- s0_s2_s4
- s0_s2_s4_s5
- s0_s2_s4_s5_s6
- s0_s2_s4_s6
- s0_s2_s5
- s0_s2_s5_s6
- s0_s2_s6
- s0_s3
- s0_s3_s4
- s0_s3_s4_s5
- s0_s3_s4_s5_s6
- s0_s3_s4_s6
- s0_s3_s5
- s0_s3_s5_s6
- s0_s3_s6
- s0_s4
- s0_s4_s5
- s0_s4_s5_s6
- s0_s4_s6
- s0_s5
- s0_s5_s6
- s0_s6
- s1
- s1_s2
- s1_s2_s3
- s1_s2_s3_s4
- s1_s2_s3_s4_s5
- s1_s2_s3_s4_s5_s6
- s1_s2_s3_s4_s6
- s1_s2_s3_s5
- s1_s2_s3_s5_s6
- s1_s2_s3_s6
- s1_s2_s4
- s1_s2_s4_s5
- s1_s2_s4_s5_s6
- s1_s2_s4_s6
- s1_s2_s5
- s1_s2_s5_s6
- s1_s2_s6
- s1_s3
- s1_s3_s4
- s1_s3_s4_s5
- s1_s3_s4_s5_s6
- s1_s3_s4_s6
- s1_s3_s5
- s1_s3_s5_s6
- s1_s3_s6
- s1_s4
- s1_s4_s5
- s1_s4_s5_s6
- s1_s4_s6
- s1_s5
- s1_s5_s6
- s1_s6
- s2
- s2_s3
- s2_s3_s4
- s2_s3_s4_s5
- s2_s3_s4_s5_s6
- s2_s3_s4_s6
- s2_s3_s5
- s2_s3_s5_s6
- s2_s3_s6
- s2_s4
- s2_s4_s5
- s2_s4_s5_s6
- s2_s4_s6
- s2_s5
- s2_s5_s6
- s2_s6
- s3
- s3_s4
- s3_s4_s5
- s3_s4_s5_s6
- s3_s4_s6
- s3_s5
- s3_s5_s6
- s3_s6
- s4
- s4_s5
- s4_s5_s6
- s4_s6
- s5
- s5_s6
- s6
clip_grad: null
clip_mode: norm
color_jitter: 0
color_mode: rgb
cooldown_epochs: 0
crop_range:
- 1.0
- 1.0
cutmix: 0
data_download: false
dataset_name: custom
decay_epochs: 90
decay_milestones:
- 90
- 180
- 270
decay_rate: 0.1
deterministic_ops: false
device: cuda
display_figures: false
distributed: false
epoch_repeats: 0
epochs: 1
eval_metric: top1
framework: torch
function_name: data_augmentation
global_seed: 123
gpu_memory_limit: 10
grad_accum_steps: 1
hardware_type: MCU
hflip: 0
horizontal_flip: 0
input_shape: &id001
- 3
- 16
- 128
input_size: *id001
interpolation: bilinear
layer_decay: null
local_rank: 0
log_interval: 10
logs_dir: logs
lr: 0.001
lr_base: 0.001
lr_base_scale: sqrt
lr_base_size: 32
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean:
- 0
- 0
- 0
min_lr: 1.0e-05
mixup: 0
model_name: states_cnn_pt
momentum: 0.9
no_aug: true
no_prefetcher: true
num_classes: 129
num_threads_tflite: 1
offset: 0
operation_mode: training
opt: adam
opt_betas: null
opt_eps: null
output_dir: ./pt/src/experiments_outputs/2026_05_07_00_39_05
patience_epochs: 10
pin_mem: true
prefetcher: false
pretrained: false
pretrained_dataset: null
project_name: states_detection_pt
rank: 0
ratio:
- 1.0
- 1.0
reprob: 0
saved_models_dir: saved_models
scale: 1
sched: cosine
sched_on_updates: false
seed: 123
smoothing: 0
start_epoch: 0
std:
- 1
- 1
- 1
test_path: ./datasets/states_dataset/test
trainer_name: ic_trainer
training_path: ./datasets/states_dataset/train
uri: ./pt/src/experiments_outputs/mlruns
use_case: image_classification
validation_batch_size: 32
validation_path: ./datasets/states_dataset/val
validation_split: 0.2
vertical_flip: 0
vflip: 0
warmup_epochs: 5
warmup_lr: 1.0e-05
warmup_prefix: false
weight_decay: 0.0001
worker_seeding: all
workers: 2
world_size: 1
